global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'aws_vm'
    static_configs:
      - targets: ['node1:9100']
        labels:
          cloud: "AWS"

  - job_name: 'azure_vm'
    static_configs:
      - targets: ['node2:9100']
        labels:
          cloud: "Azure"

  - job_name: 'gcp_vm'
    static_configs:
      - targets: ['node3:9100']
        labels:
          cloud: "GCP"

